/**
 * Dynamic block — saves no markup to post_content. The actual content
 * is generated by render.php on every page load, so the table of
 * contents always reflects the article's current headings.
 */

export default function save() {
	return null;
}